language: python
matrix:
  include:
  - python: 2.7
    env:
    - secure: RpIRQxfd291+jWgv66+AO9A6/FOJlU28v3TAqzzAQpVzx16MgyjTHerqC/I/UEoFrE8lHPdO4eGXaLKzX6CMW1vVJegEiHFbqtXinBj/rXsiD7EiXyLpeihs3wjSagoIDT1dOcF2O1bbVIuMr9/k3U9HPiM+9hv9/KBtVTWc/wciwiqQIAOZdLdnbr/Hv/8n706mLYmZCnF6+FwAXFseFza5hbmJzVWh9LpBYkxAnMHqDGw8ln63zgyf0xRandzQHx5j1UGzltpuiGf+kAwacNT8scICjygk+W07lBoXR7VfhysDyqxwd22jk46W+hR5xdSbDxR3umJp/MIO4CfkfQzTwltyf+z2GIctAKjNdMJ+dURkkoUh8Qr2IEvZ2DxWUUoyP7QBrnI6PI1XaKFi58UgubmDnziJ3QbJQnRsgOTEq5Tl8yYRtTzpGyPrltov2GjhoniKo/EmirwoKshdrP79AJvaF0s/XtfyC9f51W3w1GkDvSJydn5zqfC/iKolA725eodyIiZU6PTvuAiEttWci7MtAHPAxuL80JDUiGKEx3NkPj+2t82vd/rSEpxRSI8UzXJbh0yZjdtCO3ETlniGp8d6GSlBwCNf043F1RhDA8epq0MNrZT9svxABUDTHJN6NbzF5RhGG9iMljP+iDAnjaDBmIoDIteCqbeji14=
    - secure: B1Yytt08wNkA2paR7YsmIOkOo27PRlLXVdryso3tgTNI81y08FrtA9325HjjLF8bUe9CpbKuLgy32HslUdH4STD1Uv+A3p/U2FiCYlsXzWyAxPOEAu3/RoDwqVJHsYtbtyJo7cQ62Lus7mWcjIiViGGQUbeHsvngvqAr5Q58yKmEgTOFibQeePohAfuRzxUOPVwOa0WbaNsVwqazftl8+Nsv4roscq1dk0pIXbf3PPbvRvd49BKFWJqyyi7feQqM0yrdWciFRJ7FGsywseJSQVncIQdRj8o3IWpIbSEXceZZji/BnC/a4rQPsVXjxeaeukdZZkxf4lCNeddXhyHfHQNk5Q91rJF/ddSfZX/S79WVRDAf81YrAmAdhKdSvHUpyoiswUJ/j+bc4b/4QUVZI9Wj5eRtpygMOm04blOSDKh9KssoQXj8g+IdKQoBMiZSetkCIFtgMmoDkcaeOCFAadYGQXuUw2r/dRcopoG3GvDK6bLKY9NVUBIFGL6lv7pnwHamxUTQmdYchrBnaG61oGU2AO6PZQmfBFvk05dH8jlk6v/bAB+gkioduJZoyGh+7+fV0AB+wuFIcRKLKJy5/zRPm0oFryJ6eMn8KmqhQ/kl1LQuBE+P9Mc+B3NFd5l1Kam7tGygL8zheE2tPzqud+qsdTRWLqOY6SZiCGf14Hs=
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
    - BOB_UPLOAD_WHEEL="--universal"
  - python: 3.3
  - python: 3.4
  - python: 3.5
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libhdf5-serial-dev libatlas-dev libatlas-base-dev liblapack-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose numpy coverage
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- ./bin/buildout buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
- ./bin/python -c 'import pkg_resources; from bob.db.celeba import get_config; print(get_config())'
- ./bin/bob_dbmanage.py celeba download
- ./bin/coverage run --source=bob.db.celeba ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- coveralls
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
